apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    receivers:
      - name: none
      - name: gmail
        email_configs:
          - send_resolved: true
            to: rahulprem512@gmail.com
            from: rahulprem512@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: rahulprem512@gmail.com
            auth_identity: rahulprem512@gmail.com
            auth_password: 9408886823
    route:
      group_by:
        - job
      receiver: none
      routes:
        - match:
                #namespace: monitoring
            severity: warning
          receiver: gmail    
